name: Validate package during PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
